# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-fasthtml-settings',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-fasthtml-settings',
                'lib_path': 'cjm_fasthtml_settings'},
  'syms': {'cjm_fasthtml_settings.core': {'cjm_fasthtml_settings.core.foo': ('core.html#foo', 'cjm_fasthtml_settings/core.py')}}}
