"""Centralized HTML ID constants for settings components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto 0
__all__ = ['HtmlIds']

# %% ../../nbs/core/html_ids.ipynb 4
from typing import Final

class HtmlIds:
    """HTML ID constants used in settings components.
    
    This class provides centralized HTML ID constants for the settings library.
    All IDs are defined as class attributes for IDE autocomplete and type checking.
    
    For IDE Support:
        IDEs like VS Code with Pylance will autocomplete these attributes and warn
        if you try to access non-existent attributes. To add app-specific IDs,
        extend this class:
        
        ```python
        class AppHtmlIds(HtmlIds):
            MAIN_CONTENT = "main-content"
            CUSTOM_SECTION = "custom-section"
        ```
    
    Note:
        The typing.Final annotation indicates these are constants that shouldn't
        be reassigned at runtime.
    """

    # Settings containers
    SETTINGS_CONTENT: Final[str] = "settings-content"
    SETTINGS_SIDEBAR: Final[str] = "settings-sidebar"
    ALERT_CONTAINER: Final[str] = "alert-container"

    # Navigation and menu
    SIDEBAR_MENU: Final[str] = "sidebar-menu"

    @staticmethod
    def menu_item(name: str) -> str:
        """Generate a menu item ID for a given settings name."""
        return f"menu-item-{name}"

    @staticmethod
    def as_selector(id_str: str) -> str:
        """Convert an ID to a CSS selector format (with #)."""
        return f"#{id_str}"
