"""Centralized HTML ID constants for settings components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto 0
__all__ = ['HtmlIds']

# %% ../../nbs/core/html_ids.ipynb 4
class HtmlIds:
    """HTML ID constants used in settings components."""

    # Settings containers
    SETTINGS_CONTENT = "settings-content"
    SETTINGS_SIDEBAR = "settings-sidebar"
    ALERT_CONTAINER = "alert-container"

    # Navigation and menu
    SIDEBAR_MENU = "sidebar-menu"

    @staticmethod
    def menu_item(name: str) -> str:
        """Generate a menu item ID for a given settings name."""
        return f"menu-item-{name}"

    @staticmethod
    def as_selector(id_str: str) -> str:
        """Convert an ID to a CSS selector format (with #)."""
        return f"#{id_str}"
